name: ğŸš€ ë°°í¬
description: ë°°í¬ì™€ ê´€ë ¨ëœ ì‘ì—…ì´ í•„ìš”í•œê°€ìš”?
labels: ["âš™ï¸ ë°ë¸Œì˜µìŠ¤"]
projects: ["GU-99/1"]
body:
  - type: textarea
    attributes:
      label: ğŸ¯ ì‘ì—… ëª©í‘œ
      description: "ì´ ì‘ì—…ì˜ ëª©í‘œì™€ ê¸°ëŒ€ ê²°ê³¼ë¥¼ ì„¤ëª…í•´ì£¼ì„¸ìš”."
      placeholder: "ì˜ˆ: ë°°í¬ ì‹œê°„ì„ ë‹¨ì¶•í•˜ê¸° ìœ„í•´ ìŠ¤í¬ë¦½íŠ¸ë¥¼ ìµœì í™”, ë°°í¬ ê³¼ì •ì—ì„œ ë°œìƒí•˜ëŠ” ì˜¤ë¥˜ë¥¼ ì¤„ì´ê¸° ìœ„í•´ íŒŒì´í”„ë¼ì¸ ìˆ˜ì • ë“±"
    validations:
      required: true

  - type: textarea
    attributes:
      label: âœ… ì‘ì—…í•  ë‚´ìš©
      description: "ì‘ì—…ì„ ìˆ˜í–‰í•˜ê¸° ìœ„í•œ ë‹¨ê³„ë¥¼ ìƒì„¸íˆ ì„¤ëª…í•´ì£¼ì„¸ìš”."
      placeholder: |
        1. ê¸°ì¡´ ë°°í¬ ìŠ¤í¬ë¦½íŠ¸ ë¶„ì„
        2. ìƒˆë¡œìš´ ìŠ¤í¬ë¦½íŠ¸ ì‘ì„± ë° í…ŒìŠ¤íŠ¸
        3. í…ŒìŠ¤íŠ¸ í™˜ê²½ì—ì„œ ë°°í¬ ì‹œë®¬ë ˆì´ì…˜
        4. ì‹¤ì œ ë°°í¬ í™˜ê²½ì—ì„œ í…ŒìŠ¤íŠ¸
      render: bash
    validations:
      required: true

  - type: textarea
    attributes:
      label: ğŸ“š ì°¸ê³  ìë£Œ
      description: "ì‘ì—…ê³¼ ê´€ë ¨í•´ì„œ ì°¸ê³ í•  ë§Œí•œ ìë£Œë‚˜ ë§í¬ê°€ ìˆë‹¤ë©´ ì œê³µí•´ì£¼ì„¸ìš”."
      placeholder: "ì°¸ê³ í•  ìë£Œë‚˜ ë§í¬ë¥¼ ì…ë ¥í•´ì£¼ì„¸ìš”."
    validations:
      required: false

  - type: input
    attributes:
      label: â° ì¶”ì • ì‹œê°„
      description: "ì‘ì—…ì— ì˜ˆìƒë˜ëŠ” ì†Œìš” ì‹œê°„ì„ ì…ë ¥í•´ì£¼ì„¸ìš”."
      placeholder: "ì˜ˆ: 1ì‹œê°„"
    validations:
      required: true

  - type: input
    attributes:
      label: â° ì†Œìš” ì‹œê°„
      description: "ì‘ì—…ì— ì‹¤ì œë¡œ ì†Œìš”ëœ ì‹œê°„ì„ ì…ë ¥í•´ì£¼ì„¸ìš”."
      placeholder: "ì˜ˆ: 1.5ì‹œê°„"
    validations:
      required: false
