name: ğŸ› ï¸ í™˜ê²½ì„¤ì •
description: ì¶”ê°€ì ì¸ í™˜ê²½ì„¤ì •ì´ í•„ìš”í•œê°€ìš”?
labels: ["ğŸ› ï¸ ì„¤ì •"]
projects: ["GU-99/1"]
body:
  - type: textarea
    attributes:
      label: ğŸ¤” ì„¤ëª…
      description: "í˜„ì¬ ì–´ë–¤ ìƒí™©ì¸ì§€ ì„¤ëª…í•´ ì£¼ì„¸ìš”."
      placeholder: "ìì„¸íˆ ì ì„ìˆ˜ë¡ ì¢‹ìŠµë‹ˆë‹¤!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: âœ… ì‘ì—…í•  ë‚´ìš©
      description: "ì¶”ê°€í•  í™˜ê²½ì„¤ì •ì— ëŒ€í•´ ê°„ëµíˆ ê¸°ë¡í•´ ì£¼ì„¸ìš”."
      placeholder: "ìµœëŒ€í•œ ì„¸ë¶„í™” í•´ì„œ ì ì–´ì£¼ì„¸ìš”!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: ğŸ“š ì°¸ê³  ìë£Œ
      description: "ì‘ì—…ê³¼ ê´€ë ¨í•´ì„œ ì°¸ê³ í•  ë§Œí•œ ìë£Œë‚˜ ë§í¬ê°€ ìˆë‹¤ë©´ ì œê³µí•´ì£¼ì„¸ìš”."
      placeholder: "ì°¸ê³ í•  ìë£Œë‚˜ ë§í¬ë¥¼ ì…ë ¥í•´ì£¼ì„¸ìš”."
    validations:
      required: false

  - type: textarea
    attributes:
      label: â° ì¶”ì • ì‹œê°„
      description: "í™˜ê²½ì„¤ì •ì„ ì¶”ê°€í•˜ê¸° ìœ„í•œ ì¶”ì • ì‹œê°„ì— ëŒ€í•´ ì‘ì„±í•´ì£¼ì„¸ìš”."
      placeholder: "ì˜ˆ: 1ì‹œê°„"
    validations:
      required: true

  - type: textarea
    attributes:
      label: â° ì†Œìš” ì‹œê°„
      description: "í™˜ê²½ì„¤ì • ì¶”ê°€ ì†Œìš” ì‹œê°„ì— ëŒ€í•´ ì‘ì„±í•´ì£¼ì„¸ìš”."
      placeholder: "ì˜ˆ: 1.5ì‹œê°„"
    validations:
      required: false
